# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [12]:
#code here
import numpy as np
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)
print("After Reshape")
newarr=arr.reshape(3,4)
newarr

[ 1  2  3  4  5  6  7  8  9 10 11 12]
After Reshape


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
arr1=np.array([[1,2,3],[5,6,7]])
arr2=np.array([[2,3,4],[8,7,6]])
vercon=np.concatenate((arr1, arr2), axis=0)
print(vercon)
print()
horcon=np.concatenate((arr1, arr2), axis=1)
print(horcon)

[[1 2 3]
 [5 6 7]
 [2 3 4]
 [8 7 6]]

[[1 2 3 2 3 4]
 [5 6 7 8 7 6]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [16]:
#code here
def classify_emails(emails):
    important_keywords = ['urgent', 'important', 'announcement']
    promotions_keywords = ['sale', 'discount', 'promotion']
    spam_keywords = ['free', 'lottery', 'won', 'win']

    important_list = []
    promotions_list = []
    spam_list = []

    for email in emails:
        if any(keyword in email.lower() for keyword in important_keywords):
            important_list.append(email)
        elif any(keyword in email.lower() for keyword in promotions_keywords):
            promotions_list.append(email)
        elif any(keyword in email.lower() for keyword in spam_keywords):
            spam_list.append(email)

    return important_list, promotions_list, spam_list

emails = [
    "Urgent: Please review the proposal",
    "Get 50% off on all items this Eid!",
    "Congratulations! You've won a lottery",
    "Important: Your account needs verification",
    "Eid discount just for you!",
    "Cheap Iphone for sale - limited time offer"
]

important_emails, promotions_emails, spam_emails = classify_emails(emails)

print("Important emails:")
for email in important_emails:
    print("-", email)

print("\nPromotions emails:")
for email in promotions_emails:
    print("-", email)

print("\nSpam emails:")
for email in spam_emails:
    print("-", email)


Important emails:
- Urgent: Please review the proposal
- Important: Your account needs verification

Promotions emails:
- Eid discount just for you!
- Cheap Iphone for sale - limited time offer

Spam emails:
- Congratulations! You've won a lottery


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [19]:
#code here
english_spanish = {
"house": "casa",
"car": "coche",
"tree": "árbol",
"water": "agua",
"sun": "sol",
"moon": "luna",
"friend": "amigo",
"family": "familia",
"food": "comida",
"school": "escuela",
"teacher": "profesor/profesora",
"student": "estudiante",
"computer": "computadora",
"phone": "teléfono",
"music": "música",
"movie": "película",
"beach": "playa",
"mountain": "montaña",
"city": "ciudad",
"shirt": "camisa",
"shoes": "zapatos",
"table": "mesa",
"chair": "silla",
"bed": "cama",
"window": "ventana",
"door": "puerta",
"bathroom": "baño",
"kitchen": "cocina",
"to eat": "comer",
"to drink": "beber",
"to sleep": "dormir",
"to talk": "hablar",
"to listen": "escuchar",
"to read": "leer",
"to write": "escribir",
"to walk": "caminar",
"to run": "correr",
"to swim": "nadar",
"to dance": "bailar",
"to sing": "cantar",
"to laugh": "reír",
"to cry": "llorar",
"to love": "amar",
"to hate": "odiar",
"to learn": "aprender",
"to teach": "enseñar",
"to work": "trabajar",
"to play": "jugar",
"to watch": "ver",
"to buy": "comprar",
"to sell": "vender",
"to cook": "cocinar",
"to clean": "limpiar",
"to drive": "conducir",
"to fly": "volar",
"to travel": "viajar",
"to study": "estudiar",
"to understand": "entender",
"to speak": "hablar",
"to listen": "escuchar",
"to read": "leer",
"to write": "escribir",
"to walk": "caminar",
"to run": "correr",
"to swim": "nadar",
"to dance": "bailar",
"to sing": "cantar",
"to laugh": "reír",
"to cry": "llorar",
"to love": "amar",
"to hate": "odiar",
"to learn": "aprender",
"to teach": "enseñar",
"to work": "trabajar",
"to play": "jugar",
"to watch": "ver",
"to buy": "comprar",
"to sell": "vender",
"to cook": "cocinar",
"to clean": "limpiar",
"to drive": "conducir",
"to fly": "volar",
"to travel": "viajar",
"to study": "estudiar",
"to understand": "entender"
}

def translate_word(word):
    if word in english_spanish:
        return english_spanish[word]
    else:
        return "Translation not available."

while True:
    word = input("Enter an English word or type 'exit' to quit the dictionary: ")
    word = word.lower()
    if word == 'exit':
        print("Dictionary Closed.")
        break

    translation = translate_word(word)
    print(f"The Spanish translation of '{word}' is: {translation}")


Enter an English word or type 'exit' to quit the dictionary: book
The Spanish translation of 'book' is: Translation not available.
Enter an English word or type 'exit' to quit the dictionary: love
The Spanish translation of 'love' is: Translation not available.
Enter an English word or type 'exit' to quit the dictionary: to love
The Spanish translation of 'to love' is: amar
Enter an English word or type 'exit' to quit the dictionary: exit
Dictionary Closed.


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [22]:
import pandas as pd
import numpy as np

path = "https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv"
df = pd.read_csv(path)
print(df)

        Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sport

In [36]:
totalsales = df['Global_Sales'].sum()
print("Total global sales:", totalsales)

Total global sales: 8920.44


In [35]:
gamesale = df.loc[df['Global_Sales'].idxmax()]
print("Game with the highest global sales:\n",gamesale)


Game with the highest global sales:
 Rank                     1
Name            Wii Sports
Platform               Wii
Year                2006.0
Genre               Sports
Publisher         Nintendo
NA_Sales             41.49
EU_Sales             29.02
JP_Sales              3.77
Other_Sales           8.46
Global_Sales         82.74
Name: 0, dtype: object


In [37]:
average = df[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean()
print("Average sales for each region:\n",average)

Average sales for each region:
 NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64


In [28]:
genres = df.groupby('Genre')['Global_Sales'].sum().nlargest(5)
print("Top 5 most popular game genres based on global sales:\n",genres)

Top 5 most popular game genres based on global sales:
 Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64


In [29]:
total = df.groupby('Genre').agg({'NA_Sales': 'sum', 'EU_Sales': 'sum', 'JP_Sales': 'sum', 'Other_Sales': 'sum'})
print("Total sales for each genre in each region:\n",total)

Total sales for each genre in each region:
               NA_Sales  EU_Sales  JP_Sales  Other_Sales
Genre                                                  
Action          877.83    525.00    159.95       187.38
Adventure       105.80     64.13     52.07        16.81
Fighting        223.59    101.32     87.35        36.68
Misc            410.24    215.98    107.76        75.32
Platform        447.05    201.63    130.77        51.59
Puzzle          123.78     50.78     57.31        12.55
Racing          359.42    238.39     56.69        77.27
Role-Playing    327.28    188.06    352.31        59.61
Shooter         582.60    313.27     38.28       102.69
Simulation      183.31    113.38     63.70        31.52
Sports          683.35    376.85    135.37       134.97
Strategy         68.70     45.34     49.46        11.36


In [32]:
popular_genre = total['NA_Sales'].idxmax()
print("Most popular genre in North America (NA_Sales):", popular_genre)

Most popular genre in North America (NA_Sales): Action


In [33]:
print('Last 10 rows: \n',df.tail(10))

Last 10 rows: 
         Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   

In [34]:
top_plat = df.groupby('Platform')['Global_Sales'].sum().nlargest(3)
print("Top 3 gaming platforms with the highest global sales:\n",top_plat)

Top 3 gaming platforms with the highest global sales:
 Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


In [39]:
totalsales_genre = df.groupby('Genre')['Global_Sales'].sum()
market_share = (totalsales_genre / totalsales) * 100
print("Market share for each genre:\n", market_share)

Market share for each genre:
 Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64


In [40]:
cor_coef = df['NA_Sales'].corr(df['EU_Sales'])
print("Correlation coefficient between NA_Sales and EU_Sales:", cor_coef)


Correlation coefficient between NA_Sales and EU_Sales: 0.7677267483702631


Some tree example

In [ ]:
# import pandas as pd

# # Create a DataFrame to represent a tree
# data = {
#     'node': ['A', 'B', 'C', 'D', 'E', 'F'],
#     'parent': [None, 'A', 'A', 'B', 'B', 'C']
# }
# df = pd.DataFrame(data)

# print(df)


In [ ]:
# pip install networkx


In [ ]:
# import pandas as pd
# import networkx as nx
# import matplotlib.pyplot as plt

# # Create a DataFrame representing edges in a graph
# data = {
#     'from': ['A', 'A', 'B', 'C', 'D'],
#     'to': ['B', 'C', 'D', 'E', 'E']
# }
# edges = pd.DataFrame(data)

# # Create a graph from the edges DataFrame
# G = nx.from_pandas_edgelist(edges, 'from', 'to')

# # Draw the graph
# nx.draw(G, with_labels=True)
# plt.show()

# # Analyze the graph
# print("Nodes:", G.nodes())
# print("Edges:", G.edges())
# print("Degree for each Node:", dict(G.degree()))
